version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.php.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
      - ./data:/data
#      - logs:/var/log/nginx/error.log
#      - ./data/logs/nginx/access.log:/var/log/nginx/access.log
  php:
    build:
      context: .
      dockerfile: ./config/NGINX.PHP.Dockerfile
#      image: php:fpm
      # latest
    # image: php:7.4-fpm
    #image: php:7.3-fpm
    #image: php:8.0-fpm
    volumes:
        - ./app:/app
        - ./data:/data
#      logs:
#        driver: local
#        driver_opts:
#          type: 'none'
#          o: 'bind'
#          device: '/data/logs/nginx/error.log'

