version: '3.7'

services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
      - ./data:/data
    networks:
      - docker-simple
    links:
      - php
      - mysql
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./config/PHP.Dockerfile
    volumes:
      - ./app:/app
      - ./data:/data
      - ./data/logs/php:/var/log
    networks:
      - docker-simple
    links:
      - mysql:mysql
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/logs/mysql:/var/log/mysql
    networks:
      - docker-simple
    expose:
      - "3306"
    ports:
      - "3306"

  phpmyadmin:
    container_name: phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: password123
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    networks:
      - docker-simple

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - docker-simple

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - docker-simple

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./data/redis:/data

#  api:
#    container_name: quotes-api
#    build:
#      context: ./
#      target: production
#    image: quotes-api
#    depends_on:
#      - mysql
#      - redis
#    ports:
#      - 3000:3000
#    environment:
#      NODE_ENV: production
#      DB_HOST: mysql
#      DB_PORT: 3306
#      DB_USER: root
#      DB_PASSWORD: password123
#      DB_NAME: redis
#      REDIS_HOST: cache
#      REDIS_PORT: 6379
#      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    links:
#      - mysql
#      - redis
#    volumes:
#      - ./data/api:/src

networks:
  docker-simple:

#volumes:
#  esdata1:
#    driver: local
#  esdata2:
#    driver: local
#  mysqldata:
