version: '3.7'

services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.php.mysql.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
      - ./data:/data
    networks:
      - docker-simple
    links:
      - php
      - mysql
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./config/NGINX.PHP.MySQL.Dockerfile
    volumes:
      - ./app:/app
      - ./data:/data
      - ./data/logs/php:/var/log
    networks:
      - docker-simple
    links:
      - mysql:mysql
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/logs/mysql:/var/log/mysql
    networks:
      - docker-simple
    expose:
      - "3306"
    ports:
      - "3306"

  phpmyadmin:
    container_name: phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: password123
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    networks:
      - docker-simple

networks:
  docker-simple:

#volumes:
#  mysqldata:
